[tool.poetry]
name = "llm-tui"
version = "0.1.0"
description = ""
authors = ["roofspirit"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.9"
requests = "^2.32.3"
rich = "^13.9.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
